/**
 * Multi-Language Model Code Generator
 * Translates JSON-based database schemas into native data structure templates for TS, C#, Python, and Go.
 */

import { Schema } from '../types.js';

/**
 * Compiles a database schema into native model definitions for the specified programming language.
 *
 * @param schema Standardized database schema JSON representation
 * @param lang Target programming language selector
 * @returns Source code string defining classes/structs/interfaces
 */
export function generateModels(
  schema: Schema,
  lang: 'typescript' | 'csharp' | 'python' | 'go'
): string {
  switch (lang) {
    case 'typescript':
      return generateTypeScript(schema);
    case 'csharp':
      return generateCSharp(schema);
    case 'python':
      return generatePython(schema);
    case 'go':
      return generateGo(schema);
    default:
      throw new Error(`Unsupported model generation language: ${lang}`);
  }
}

// Convert column name to PascalCase for C# and Go
function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (m) => m.toUpperCase());
}

// TypeScript Generator
function generateTypeScript(schema: Schema): string {
  const blocks: string[] = [];

  for (const table of schema.tables) {
    const interfaceName = toPascalCase(table.name);
    const lines: string[] = [];

    lines.push(`export interface ${interfaceName} {`);
    for (const col of table.columns) {
      let tsType = 'any';
      const colType = col.type.toUpperCase();

      if (
        colType.includes('INT') ||
        colType.includes('SERIAL') ||
        colType.includes('NUMERIC') ||
        colType.includes('DECIMAL') ||
        colType.includes('REAL') ||
        colType.includes('DOUBLE')
      ) {
        tsType = 'number';
      } else if (colType.includes('CHAR') || colType.includes('TEXT') || colType.includes('UUID')) {
        tsType = 'string';
      } else if (colType.includes('BOOL')) {
        tsType = 'boolean';
      } else if (colType.includes('DATE') || colType.includes('TIME')) {
        tsType = 'Date | string';
      }

      const opt = col.nullable ? '?' : '';
      lines.push(`  ${col.name}${opt}: ${tsType};`);
    }
    lines.push('}');
    blocks.push(lines.join('\n'));
  }

  return `// Generated by DbSlate\n\n` + blocks.join('\n\n') + '\n';
}

// C# Generator
function generateCSharp(schema: Schema): string {
  const blocks: string[] = [];

  for (const table of schema.tables) {
    const className = toPascalCase(table.name);
    const lines: string[] = [];

    lines.push(`public class ${className}`);
    lines.push('{');

    for (const col of table.columns) {
      let csType = 'object';
      const colType = col.type.toUpperCase();

      if (colType.includes('INT') || colType.includes('SERIAL')) {
        csType = colType.includes('BIG') ? 'long' : 'int';
      } else if (colType.includes('NUMERIC') || colType.includes('DECIMAL')) {
        csType = 'decimal';
      } else if (colType.includes('REAL') || colType.includes('DOUBLE')) {
        csType = 'double';
      } else if (colType.includes('CHAR') || colType.includes('TEXT') || colType.includes('UUID')) {
        csType = 'string';
      } else if (colType.includes('BOOL')) {
        csType = 'bool';
      } else if (colType.includes('DATE') || colType.includes('TIME')) {
        csType = 'DateTime';
      }

      const opt = col.nullable && csType !== 'string' ? '?' : '';
      const propName = toPascalCase(col.name);

      lines.push(`    public ${csType}${opt} ${propName} { get; set; }`);
    }

    lines.push('}');
    blocks.push(lines.join('\n'));
  }

  return (
    `// Generated by DbSlate\nusing System;\n\nnamespace DbSlate.Models\n{\n` +
    blocks
      .map((b) =>
        b
          .split('\n')
          .map((l) => '    ' + l)
          .join('\n')
      )
      .join('\n\n') +
    '\n}\n'
  );
}

// Python Generator (Pydantic V2)
function generatePython(schema: Schema): string {
  const blocks: string[] = [];

  for (const table of schema.tables) {
    const className = toPascalCase(table.name);
    const lines: string[] = [];

    lines.push(`class ${className}(BaseModel):`);
    for (const col of table.columns) {
      let pyType = 'Any';
      const colType = col.type.toUpperCase();

      if (colType.includes('INT') || colType.includes('SERIAL')) {
        pyType = 'int';
      } else if (
        colType.includes('NUMERIC') ||
        colType.includes('DECIMAL') ||
        colType.includes('REAL') ||
        colType.includes('DOUBLE')
      ) {
        pyType = 'float';
      } else if (colType.includes('CHAR') || colType.includes('TEXT') || colType.includes('UUID')) {
        pyType = 'str';
      } else if (colType.includes('BOOL')) {
        pyType = 'bool';
      } else if (colType.includes('DATE') || colType.includes('TIME')) {
        pyType = 'datetime';
      }

      if (col.nullable) {
        lines.push(`    ${col.name}: Optional[${pyType}] = None`);
      } else {
        lines.push(`    ${col.name}: ${pyType}`);
      }
    }
    blocks.push(lines.join('\n'));
  }

  return (
    `# Generated by DbSlate\nfrom datetime import datetime\nfrom typing import Optional, Any\nfrom pydantic import BaseModel\n\n\n` +
    blocks.join('\n\n\n') +
    '\n'
  );
}

// Go Generator
function generateGo(schema: Schema): string {
  const blocks: string[] = [];
  let needsTimeImport = false;

  for (const table of schema.tables) {
    const structName = toPascalCase(table.name);
    const lines: string[] = [];

    lines.push(`type ${structName} struct {`);
    for (const col of table.columns) {
      let goType = 'interface{}';
      const colType = col.type.toUpperCase();

      if (colType.includes('INT') || colType.includes('SERIAL')) {
        goType = colType.includes('BIG') ? 'int64' : 'int';
      } else if (
        colType.includes('NUMERIC') ||
        colType.includes('DECIMAL') ||
        colType.includes('REAL') ||
        colType.includes('DOUBLE')
      ) {
        goType = 'float64';
      } else if (colType.includes('CHAR') || colType.includes('TEXT') || colType.includes('UUID')) {
        goType = 'string';
      } else if (colType.includes('BOOL')) {
        goType = 'bool';
      } else if (colType.includes('DATE') || colType.includes('TIME')) {
        goType = 'time.Time';
        needsTimeImport = true;
      }

      // If nullable, use pointers to represent null values in Go
      const ptr = col.nullable ? '*' : '';
      const fieldName = toPascalCase(col.name);

      lines.push(`\t${fieldName} ${ptr}${goType} \`json:"${col.name}" db:"${col.name}"\``);
    }
    lines.push('}');
    blocks.push(lines.join('\n'));
  }

  const imports = needsTimeImport ? '\nimport (\n\t"time"\n)\n' : '';

  return `// Generated by DbSlate\npackage models\n${imports}\n` + blocks.join('\n\n') + '\n';
}
